# Change these first
owner: atnauman # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Psyshare service
    url: https://psyshare.bihealth.org
  - name: Mellite service
    url: https://mellite.bihealth.org
  - name: Spacehack service
    url: https://spacehack.bihealth.org
  - name: Cloud Platforum (Sandbox)
    url: https://sandbox.bihealth.org
  - name: Sandbox API endpoint with data
    method: POST
    url: https://sandbox.bihealth.org/hub/login
    headers:
      - "Content-Type: application/json"
    body: '{ "password": "hello" }'  
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime (Service Status)
  introTitle: "**Service Status** is monitor and status page for data management group services."
  introMessage: This status page shows **real-time** data from the listed services. No server required — just GitHub Actions, Issues, and Pages. For adding your service for status check or reporting an issue please write me at: tauseef.nauman@bih-charite.de
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
